//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinema_uygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class bilet
    {
        public int bilet_id { get; set; }
        public Nullable<int> film_id { get; set; }
        public Nullable<int> seans_id { get; set; }
        public System.DateTime tarih { get; set; }
        public string koltuk_no { get; set; }
        public decimal ucret { get; set; }
    
        public virtual film film { get; set; }
        public virtual seans seans { get; set; }
    }
}
