//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinema_uygulaması
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinemaEntities : DbContext
    {
        public SinemaEntities()
            : base("name=SinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bilet> bilet { get; set; }
        public virtual DbSet<film> film { get; set; }
        public virtual DbSet<salon> salon { get; set; }
        public virtual DbSet<seans> seans { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
